# Generated by Django 4.2.27 on 2026-02-01 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_email_user_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='eds_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Groupe EDS'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
