# Generated by Django 4.2.28 on 2026-02-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_ine_add_date_naissance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_last_na_b34e19_idx',
            old_name='students_st_last_na_idx',
        ),
    ]
