# Generated by Django 4.2.27 on 2026-02-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_birth_date'),
        ('students', '0004_rename_students_st_last_na_idx_students_st_last_na_b34e19_idx'),
    ]

    operations = [
    ]
