# Generated by Django 4.2.27 on 2026-02-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_merge_20260211_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
    ]
