# Generated by Django 4.2.27 on 2026-02-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_privacy_charter_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_full_na_6ea9f7_idx',
            old_name='students_st_full_na_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_email_e271bc_idx',
            old_name='students_st_email_idx',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Classe'),
        ),
    ]
