# Generated by Django 4.2.27 on 2026-02-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
    ]
