# Generated by Django 4.2.27 on 2026-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_student_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Groupe'),
        ),
    ]
