# Generated by Django 4.2.27 on 2026-01-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_refactor_annotation_and_add_grading_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="annotation",
            new_name="grading_ann_copy_id_35b843_idx",
            old_name="grading_ann_copy_id_f6ec3e_idx",
        ),
        migrations.RenameIndex(
            model_name="gradingevent",
            new_name="grading_gra_copy_id_160cd8_idx",
            old_name="grading_gra_copy_id_c7a0e0_idx",
        ),
        migrations.AlterField(
            model_name="gradingevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("IMPORT", "Import Copie"),
                    ("VALIDATE", "Validation (STAGING→READY)"),
                    ("LOCK", "Verrouillage (READY→LOCKED)"),
                    ("UNLOCK", "Déverrouillage (LOCKED→READY)"),
                    ("CREATE_ANN", "Création Annotation"),
                    ("UPDATE_ANN", "Modification Annotation"),
                    ("DELETE_ANN", "Suppression Annotation"),
                    ("FINALIZE", "Finalisation (LOCKED→GRADED)"),
                    ("EXPORT", "Export PDF"),
                ],
                max_length=20,
                verbose_name="Action",
            ),
        ),
    ]
