# Generated by production readiness fixes - 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_annotation_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='version',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Numéro de version pour le verrouillage optimiste',
                verbose_name='Version'
            ),
        ),
    ]
