# Generated by Django 4.2.27 on 2026-01-22 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_alter_exam_pdf_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "grading",
            "0003_rename_grading_ann_copy_id_f6ec3e_idx_grading_ann_copy_id_35b843_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CopyLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Token de session",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Verrouillé le"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="Expire le"),
                ),
                (
                    "copy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to="exams.copy",
                        verbose_name="Copie",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_locks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verrou de copie",
                "verbose_name_plural": "Verrous de copies",
            },
        ),
    ]
