# Generated by Django 4.2.27 on 2026-01-22 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0007_alter_exam_pdf_source"),
        ("grading", "0004_copylock"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Etat complet de l'éditeur (annotations, texte en cours)",
                        verbose_name="Contenu Draft",
                    ),
                ),
                (
                    "lock_token",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="Token de verrou associé"
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="ID Client (Anti-écrasement)",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Version"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="exams.copy",
                        verbose_name="Copie",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_drafts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Propriétaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brouillon de correction",
                "verbose_name_plural": "Brouillons de correction",
                "unique_together": {("copy", "owner")},
            },
        ),
    ]
