# Generated by Django 4.2.27 on 2026-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_draftstate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='copylock',
            index=models.Index(fields=['expires_at'], name='idx_copylock_expires_at'),
        ),
        migrations.AddIndex(
            model_name='copylock',
            index=models.Index(fields=['owner'], name='idx_copylock_owner'),
        ),
        migrations.AddIndex(
            model_name='copylock',
            index=models.Index(fields=['copy'], name='idx_copylock_copy'),
        ),
        migrations.AddConstraint(
            model_name='copylock',
            constraint=models.UniqueConstraint(fields=('copy',), name='uniq_copylock_copy'),
        ),
    ]
