# Generated by Django 4.2.27 on 2026-01-29 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_remove_copy_exams_copy_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0007_annotation_optimistic_locking'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text='Identifiant de la question dans le barème', max_length=255, verbose_name='Identifiant de question')),
                ('remark', models.TextField(help_text='Commentaire facultatif du correcteur', verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_remarks', to='exams.copy', verbose_name='Copie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_remarks_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Remarque de question',
                'verbose_name_plural': 'Remarques de questions',
                'indexes': [models.Index(fields=['copy', 'question_id'], name='grading_que_copy_id_d5f133_idx')],
                'unique_together': {('copy', 'question_id')},
            },
        ),
    ]
