# Generated by Django 4.2.27 on 2026-01-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_questionremark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionremark',
            name='question_id',
            field=models.CharField(help_text='Identifiant de la question dans le barème', max_length=255, verbose_name='ID de la question'),
        ),
        migrations.AlterField(
            model_name='questionremark',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remarque'),
        ),
    ]
