# Generated by Django 4.2.27 on 2026-02-11 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_add_exam_timestamps'),
        ('grading', '0009_alter_questionremark_question_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scores_data', models.JSONField(help_text='Structure JSON contenant les scores par question', verbose_name='Détail des notes')),
                ('final_comment', models.TextField(blank=True, verbose_name='Appréciation Générale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.copy', verbose_name='Copie')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
            },
        ),
    ]
