# Generated by Django 4.2.27 on 2026-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_alter_questionremark_question_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='annotation',
            new_name='ann_copy_page_idx',
            old_name='grading_ann_copy_id_35b843_idx',
        ),
        migrations.RenameIndex(
            model_name='gradingevent',
            new_name='event_copy_time_idx',
            old_name='grading_gra_copy_id_160cd8_idx',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['created_by', 'created_at'], name='ann_creator_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gradingevent',
            index=models.Index(fields=['actor', 'action'], name='event_actor_action_idx'),
        ),
    ]
