# Generated by Django 4.2.27 on 2026-02-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_exam_student_csv_alter_copy_status'),
        ('grading', '0011_questionscore'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionscore',
            name='unique_copy_question_score',
        ),
        migrations.RenameIndex(
            model_name='questionscore',
            new_name='grading_que_copy_id_4e072a_idx',
            old_name='grading_que_copy_id_8a1b2c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='questionscore',
            unique_together={('copy', 'question_id')},
        ),
    ]
