# Generated by Django 4.2.27 on 2026-02-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0021_annotation_bank_and_documents'),
        ('grading', '0011_annotation_type_french'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name="Texte de l'annotation")),
                ('exercise_context', models.PositiveIntegerField(blank=True, help_text="Numéro d'exercice associé (optionnel)", null=True, verbose_name='Contexte exercice')),
                ('question_context', models.CharField(blank=True, help_text='Label de question associé (optionnel)', max_length=20, verbose_name='Contexte question')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_annotations', to=settings.AUTH_USER_MODEL, verbose_name='Correcteur')),
            ],
            options={
                'verbose_name': 'Annotation personnelle',
                'verbose_name_plural': 'Annotations personnelles',
                'ordering': ['-usage_count', '-last_used'],
                'indexes': [models.Index(fields=['user', '-usage_count'], name='grading_use_user_id_c401d6_idx'), models.Index(fields=['user', 'exercise_context'], name='grading_use_user_id_2aa04d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnotationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_number', models.PositiveIntegerField(verbose_name="Numéro d'exercice")),
                ('question_number', models.CharField(help_text="Ex: '1', '3b', 'A.1'", max_length=20, verbose_name='Numéro de question')),
                ('sub_question', models.CharField(blank=True, help_text="Ex: 'a', 'ii', etc.", max_length=20, verbose_name='Sous-question')),
                ('criterion_type', models.CharField(choices=[('method', 'Méthode'), ('result', 'Résultat'), ('justification', 'Justification'), ('redaction', 'Rédaction'), ('error_typique', 'Erreur typique'), ('bonus', 'Bonus'), ('plafond', 'Plafond')], max_length=30, verbose_name='Type de critère')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('mineur', 'Mineur'), ('majeur', 'Majeur'), ('critique', 'Critique')], default='info', max_length=20, verbose_name='Sévérité')),
                ('text', models.TextField(verbose_name="Texte de l'annotation")),
                ('linked_bareme_reference', models.TextField(blank=True, help_text='Extrait du barème lié à cette annotation', verbose_name='Référence barème')),
                ('linked_corrige_reference', models.TextField(blank=True, help_text='Extrait du corrigé lié à cette annotation', verbose_name='Référence corrigé')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour filtrage et recherche', verbose_name='Tags')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('document_set', models.ForeignKey(blank=True, help_text='Version des documents ayant servi à générer ce template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotation_templates', to='exams.examdocumentset', verbose_name='Lot documentaire source')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_templates', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': "Template d'annotation",
                'verbose_name_plural': "Templates d'annotation",
                'ordering': ['exercise_number', 'question_number', 'criterion_type'],
                'indexes': [models.Index(fields=['exam', 'exercise_number', 'question_number'], name='grading_ann_exam_id_272d77_idx'), models.Index(fields=['exam', 'criterion_type'], name='grading_ann_exam_id_a39905_idx')],
            },
        ),
    ]
