# Generated by Django 4.2.27 on 2026-02-08 17:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_remove_questionscore_unique_copy_question_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionscore',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='Note attribuée à cette question', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Note'),
        ),
    ]
