# Generated by Django 4.2.29 on 2026-03-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0017_alter_gradingevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingevent',
            name='action',
            field=models.CharField(choices=[('IMPORT', 'Import Copie'), ('VALIDATE', 'Validation (STAGING→READY)'), ('LOCK', 'Verrouillage (READY→LOCKED)'), ('UNLOCK', 'Déverrouillage (LOCKED→READY)'), ('CREATE_ANN', 'Création Annotation'), ('UPDATE_ANN', 'Modification Annotation'), ('DELETE_ANN', 'Suppression Annotation'), ('FINALIZE', 'Finalisation (LOCKED→GRADED)'), ('EXPORT', 'Export PDF'), ('REOPEN', 'Réouverture (GRADED→READY)'), ('SAVE_APPREC', 'Sauvegarde appréciation globale')], max_length=20, verbose_name='Action'),
        ),
    ]
