# Generated by Django 4.2.29 on 2026-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0019_reconcile_annotation_types_french'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='type',
            field=models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('SURLIGNAGE', 'Surligné'), ('ERREUR', 'Erreur'), ('BONUS', 'Bonus'), ('VRAI', 'Vrai'), ('FAUX', 'Faux')], default='COMMENTAIRE', max_length=20, verbose_name="Type d'annotation"),
        ),
        migrations.AlterField(
            model_name='gradingevent',
            name='action',
            field=models.CharField(choices=[('IMPORT', 'Import Copie'), ('VALIDATE', 'Validation (STAGING→READY)'), ('LOCK', 'Verrouillage (READY→LOCKED)'), ('UNLOCK', 'Déverrouillage (LOCKED→READY)'), ('CREATE_ANN', 'Création Annotation'), ('UPDATE_ANN', 'Modification Annotation'), ('DELETE_ANN', 'Suppression Annotation'), ('FINALIZE', 'Finalisation (LOCKED→GRADED)'), ('EXPORT', 'Export PDF'), ('REOPEN', 'Réouverture (GRADED→READY)'), ('SAVE_APPREC', 'Sauvegarde appréciation globale'), ('scores_saved', 'Notes sauvegardées'), ('remark_saved', 'Remarque sauvegardée')], max_length=20, verbose_name='Action'),
        ),
    ]
