# Generated by Django 4.2.29 on 2026-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0020_alter_annotation_type_alter_gradingevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='h',
            field=models.FloatField(default=0.1, help_text="Hauteur dans l'intervalle [0,1]", verbose_name='Hauteur normalisée'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='w',
            field=models.FloatField(default=0.1, help_text="Largeur dans l'intervalle [0,1]", verbose_name='Largeur normalisée'),
        ),
    ]
