# Generated by Django 4.2.29 on 2026-04-08 10:05

from django.db import migrations, models
import grading.models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0021_add_default_w_h_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scores_data',
            field=models.JSONField(help_text='Structure JSON contenant les scores par question', validators=[grading.models.validate_scores_data], verbose_name='Détail des notes'),
        ),
    ]
