# Generated by Django 4.2.30 on 2026-04-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0022_add_scores_data_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingevent',
            name='action',
            field=models.CharField(choices=[('IMPORT', 'Import Copie'), ('VALIDATE', 'Validation (STAGING→READY)'), ('LOCK', 'Verrouillage (READY→LOCKED)'), ('UNLOCK', 'Déverrouillage (LOCKED→READY)'), ('ROTATE_LAST_PAGE', 'Rotation dernière page'), ('CREATE_ANN', 'Création Annotation'), ('UPDATE_ANN', 'Modification Annotation'), ('DELETE_ANN', 'Suppression Annotation'), ('FINALIZE', 'Finalisation (LOCKED→GRADED)'), ('EXPORT', 'Export PDF'), ('REOPEN', 'Réouverture (GRADED→READY)'), ('SAVE_APPREC', 'Sauvegarde appréciation globale'), ('scores_saved', 'Notes sauvegardées'), ('remark_saved', 'Remarque sauvegardée')], max_length=20, verbose_name='Action'),
        ),
    ]
