# Generated by Django 4.2.29 on 2026-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0024_alter_gradingevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingevent',
            name='action',
            field=models.CharField(choices=[('IMPORT', 'Import Copie'), ('VALIDATE', 'Validation (STAGING→READY)'), ('LOCK', 'Verrouillage (READY→LOCKED)'), ('UNLOCK', 'Déverrouillage (LOCKED→READY)'), ('FINALIZE', 'Finalisation (LOCKED→GRADED)'), ('scores_saved', 'Notes sauvegardées'), ('remark_saved', 'Remarque sauvegardée'), ('REOPEN', 'Réouverture (GRADED→READY)'), ('score_corrected', 'Correction de note (après finalisation)'), ('pdf_regenerated', 'Régénération PDF final')], max_length=20, verbose_name='Action'),
        ),
    ]
