# Generated by Django 4.2.29 on 2026-05-25 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grading.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_email_unique'),
        ('exams', '0038_copy_check_copy_status_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grading', '0026_alter_gradingevent_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerReviewCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non commencée'), ('IN_PROGRESS', 'En cours'), ('FINALIZED', 'Finalisée')], default='NOT_STARTED', max_length=20, verbose_name='Statut')),
                ('scores_data', models.JSONField(blank=True, default=dict, validators=[grading.models.validate_scores_data], verbose_name='Notes proposées')),
                ('global_appreciation', models.TextField(blank=True, verbose_name='Appréciation globale proposée')),
                ('final_comment', models.TextField(blank=True, verbose_name='Commentaire final proposé')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_peer_reviews', to='students.student', verbose_name='Élève correcteur')),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_peer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur élève correcteur')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_review_corrections', to='exams.exam', verbose_name='Examen')),
                ('source_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_review_corrections', to='exams.copy', verbose_name='Copie source officielle')),
                ('supervising_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_peer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant superviseur')),
            ],
            options={
                'verbose_name': 'Correction participative',
                'verbose_name_plural': 'Corrections participatives',
            },
        ),
        migrations.CreateModel(
            name='PeerReviewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('SAVE', 'Sauvegarde'), ('FINALIZE', 'Finalisation')], max_length=20, verbose_name='Action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peer_review_events', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='grading.peerreviewcorrection', verbose_name='Correction participative')),
            ],
            options={
                'verbose_name': 'Événement de correction participative',
                'verbose_name_plural': 'Événements de correction participative',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_index', models.PositiveIntegerField(verbose_name='Index de page')),
                ('x', models.FloatField(verbose_name='Position X normalisée')),
                ('y', models.FloatField(verbose_name='Position Y normalisée')),
                ('w', models.FloatField(default=0.1, verbose_name='Largeur normalisée')),
                ('h', models.FloatField(default=0.1, verbose_name='Hauteur normalisée')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('type', models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('SURLIGNAGE', 'Surligné'), ('ERREUR', 'Erreur'), ('BONUS', 'Bonus'), ('VRAI', 'Vrai'), ('FAUX', 'Faux')], default='COMMENTAIRE', max_length=20, verbose_name='Type')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Couleur')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='grading.peerreviewcorrection', verbose_name='Correction participative')),
            ],
            options={
                'verbose_name': 'Annotation participative',
                'verbose_name_plural': 'Annotations participatives',
                'ordering': ['page_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerReviewQuestionRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255, verbose_name='ID de question')),
                ('remark', models.TextField(blank=True, verbose_name='Remarque')),
                ('points_awarded', models.FloatField(blank=True, null=True, verbose_name='Points proposés')),
                ('max_points', models.FloatField(blank=True, null=True, verbose_name='Maximum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('peer_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_remarks', to='grading.peerreviewcorrection', verbose_name='Correction participative')),
            ],
            options={
                'verbose_name': 'Remarque participative',
                'verbose_name_plural': 'Remarques participatives',
                'indexes': [models.Index(fields=['peer_review', 'question_id'], name='idx_peer_remark_review_q')],
            },
        ),
        migrations.AddConstraint(
            model_name='peerreviewquestionremark',
            constraint=models.UniqueConstraint(fields=('peer_review', 'question_id'), name='uniq_peer_remark_review_question'),
        ),
        migrations.AddIndex(
            model_name='peerreviewevent',
            index=models.Index(fields=['peer_review', 'timestamp'], name='idx_peer_event_review_time'),
        ),
        migrations.AddIndex(
            model_name='peerreviewcorrection',
            index=models.Index(fields=['exam', 'status'], name='idx_peer_review_exam_status'),
        ),
        migrations.AddIndex(
            model_name='peerreviewcorrection',
            index=models.Index(fields=['assigned_user', 'status'], name='idx_peer_review_user_status'),
        ),
        migrations.AddIndex(
            model_name='peerreviewcorrection',
            index=models.Index(fields=['supervising_teacher', 'exam'], name='idx_peer_review_teacher_exam'),
        ),
        migrations.AddConstraint(
            model_name='peerreviewcorrection',
            constraint=models.UniqueConstraint(fields=('exam', 'source_copy'), name='uniq_peer_review_exam_source_copy'),
        ),
        migrations.AddConstraint(
            model_name='peerreviewcorrection',
            constraint=models.UniqueConstraint(fields=('exam', 'assigned_student'), name='uniq_peer_review_exam_assigned_student'),
        ),
        migrations.AddConstraint(
            model_name='peerreviewcorrection',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['NOT_STARTED', 'IN_PROGRESS', 'FINALIZED'])), name='check_peer_review_status_valid'),
        ),
        migrations.AddIndex(
            model_name='peerreviewannotation',
            index=models.Index(fields=['peer_review', 'page_index'], name='idx_peer_ann_review_page'),
        ),
    ]
