# Generated by Django 4.2.29 on 2026-05-06 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0039_alter_copy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('DNB_2026', 'DNB 2026'), ('BILAN_BLANC', 'Bilan Blanc')], max_length=20)),
                ('scope', models.CharField(choices=[('ETABLISSEMENT', 'Établissement'), ('CLASSE', 'Classe'), ('GROUPE', 'Groupe')], default='ETABLISSEMENT', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('GENERATING', 'En cours de génération'), ('DONE', 'Terminé'), ('ERROR', 'Erreur')], default='PENDING', max_length=20)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bilans/%Y/%m/')),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('rag_collection', models.CharField(blank=True, max_length=100)),
                ('generation_time', models.DurationField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de bilan',
                'verbose_name_plural': 'Rapports de bilan',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='BilanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('STATS', 'Statistiques globales'), ('DOMAINS', 'Analyse par domaine'), ('QUESTIONS', 'Analyse question par question'), ('COMPETENCES', 'Maîtrise des compétences'), ('CORRECTORS', 'Analyse inter-correcteurs'), ('PROFILES', 'Profils de la promotion'), ('RECOMMENDATIONS', 'Recommandations')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.JSONField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('rag_context_used', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='bilan.bilanreport')),
            ],
            options={
                'ordering': ['order', 'section_type'],
                'unique_together': {('report', 'section_type')},
            },
        ),
    ]
