# Generated by Django 5.2.10 on 2026-01-17 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_page', models.PositiveIntegerField(verbose_name='Page de début')),
                ('end_page', models.PositiveIntegerField(verbose_name='Page de fin')),
                ('header_image', models.ImageField(help_text='Image rognée de la zone nom pour validation manuelle.', upload_to='booklets/headers/', verbose_name="Image de l'en-tête")),
                ('student_name_guess', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estimation du nom (OCR)')),
            ],
            options={
                'verbose_name': 'Fascicule',
                'verbose_name_plural': 'Fascicules',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'examen")),
                ('date', models.DateField(verbose_name="Date de l'examen")),
                ('pdf_source', models.FileField(upload_to='exams/source/', verbose_name='Fichier PDF source')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité ?')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(max_length=50, unique=True, verbose_name='Anonymat')),
                ('final_pdf', models.FileField(upload_to='copies/final/', verbose_name='PDF Final Anonymisé')),
                ('status', models.CharField(choices=[('STAGING', 'En attente'), ('READY', 'Prêt à corriger'), ('LOCKED', 'Verrouillé'), ('GRADED', 'Corrigé')], default='STAGING', max_length=20, verbose_name='Statut')),
                ('booklets', models.ManyToManyField(blank=True, related_name='assigned_copy', to='exams.booklet', verbose_name='Fascicules composants')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Copie',
                'verbose_name_plural': 'Copies',
            },
        ),
        migrations.AddField(
            model_name='booklet',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='exams.exam', verbose_name='Examen'),
        ),
    ]
