# Generated by Django 5.2.10 on 2026-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklet',
            name='pages_images',
            field=models.JSONField(blank=True, default=list, help_text='Liste des chemins des images [P1, P2, P3, P4] après split.', verbose_name='Liste des pages ordonnée'),
        ),
        migrations.AddField(
            model_name='exam',
            name='grading_structure',
            field=models.JSONField(blank=True, default=list, verbose_name='Barème (Structure JSON)'),
        ),
    ]
