# Generated by Django 5.2.10 on 2026-01-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_booklet_pages_images_exam_grading_structure'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_identified',
            field=models.BooleanField(default=False, help_text='Vrai si la copie a été associée à un élève.', verbose_name='Identifié ?'),
        ),
        migrations.AddField(
            model_name='copy',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='students.student', verbose_name='Élève identifié'),
        ),
    ]
