# Generated by Django 5.2.10 on 2026-01-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_copy_is_identified_copy_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Image rognée de la zone nom pour validation manuelle.', null=True, upload_to='booklets/headers/', verbose_name="Image de l'en-tête"),
        ),
        migrations.AlterField(
            model_name='copy',
            name='final_pdf',
            field=models.FileField(blank=True, null=True, upload_to='copies/final/', verbose_name='PDF Final Anonymisé'),
        ),
    ]
