# Generated by Django 5.2.10 on 2026-01-21 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_booklet_header_image_alter_copy_final_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='graded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp LOCKED → GRADED', null=True, verbose_name='Date de notation'),
        ),
        migrations.AddField(
            model_name='copy',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp READY → LOCKED', null=True, verbose_name='Date de verrouillage'),
        ),
        migrations.AddField(
            model_name='copy',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_copies', to=settings.AUTH_USER_MODEL, verbose_name='Verrouillé par'),
        ),
        migrations.AddField(
            model_name='copy',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp STAGING → READY', null=True, verbose_name='Date de validation'),
        ),
    ]
