# Generated by Django 4.2.27 on 2026-01-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_add_copy_traceability_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="pdf_source",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="copies/source/",
                verbose_name="Fichier PDF source",
            ),
        ),
    ]
