# Generated by Django 4.2.27 on 2026-01-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_copy_pdf_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="pdf_source",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="exams/source/",
                verbose_name="Fichier PDF source",
            ),
        ),
    ]
