# Generated by Django 4.2.27 on 2026-01-24 13:57

import django.core.validators
from django.db import migrations, models
import exams.validators


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_pdf_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='pdf_source',
            field=models.FileField(blank=True, help_text='Fichier PDF uniquement. Taille max: 50 MB', null=True, upload_to='copies/source/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), exams.validators.validate_pdf_size, exams.validators.validate_pdf_not_empty], verbose_name='Fichier PDF source'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pdf_source',
            field=models.FileField(blank=True, help_text='Fichier PDF uniquement. Taille max: 50 MB', null=True, upload_to='exams/source/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), exams.validators.validate_pdf_size, exams.validators.validate_pdf_not_empty], verbose_name='Fichier PDF source'),
        ),
    ]
