# Generated by Django 4.2.27 on 2026-01-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0009_add_advanced_pdf_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correctors',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Correcteurs assignés'),
        ),
    ]
