# Generated by Django 4.2.27 on 2026-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_correctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pages_per_booklet',
            field=models.PositiveIntegerField(default=4, help_text='Nombre de pages par copie/fascicule pour le découpage automatique.', verbose_name='Pages par fascicule'),
        ),
    ]
