# Generated by Django 4.2.27 on 2026-01-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_exam_pages_per_booklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booklets', to='exams.exam', verbose_name='Examen'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='exams.exam', verbose_name='Examen'),
        ),
    ]
