# Generated by production readiness fixes - 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_booklet_exam_alter_copy_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(
                choices=[
                    ('STAGING', 'En attente'),
                    ('READY', 'Prêt à corriger'),
                    ('LOCKED', 'Verrouillé'),
                    ('GRADING_IN_PROGRESS', 'Correction en cours'),
                    ('GRADING_FAILED', 'Échec de correction'),
                    ('GRADED', 'Corrigé')
                ],
                default='STAGING',
                max_length=20,
                verbose_name='Statut'
            ),
        ),
        migrations.AddField(
            model_name='copy',
            name='grading_error_message',
            field=models.TextField(
                blank=True,
                help_text="Détails de l'erreur si la correction échoue",
                null=True,
                verbose_name="Message d'erreur de correction"
            ),
        ),
        migrations.AddField(
            model_name='copy',
            name='grading_retries',
            field=models.IntegerField(
                default=0,
                help_text='Nombre de tentatives de correction automatique',
                verbose_name='Nombre de tentatives'
            ),
        ),
    ]
