# Generated by Django 4.2.27 on 2026-01-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_copy_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_exam_status_idx',
        ),
    ]
