# Generated by Django 4.2.27 on 2026-01-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_copy_dispatch_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_exam_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_assigned_corrector_idx',
        ),
        migrations.RemoveIndex(
            model_name='copy',
            name='exams_copy_dispatch_run_idx',
        ),
        migrations.AddField(
            model_name='copy',
            name='global_appreciation',
            field=models.TextField(blank=True, help_text='Commentaire global du correcteur pour cette copie', null=True, verbose_name='Appréciation globale'),
        ),
    ]
