# Generated by Django 4.2.27 on 2026-02-10 21:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exams.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_remove_copy_exams_copy_status_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='students_csv',
            field=models.FileField(blank=True, help_text='Fichier CSV contenant la liste des élèves (optionnel)', null=True, upload_to='exams/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Liste des élèves (CSV)'),
        ),
        migrations.AddField(
            model_name='exam',
            name='upload_mode',
            field=models.CharField(choices=[('BATCH_A3', 'Scan par lots (A3) - Découpage automatique'), ('INDIVIDUAL_A4', 'Fichiers individuels (A4) - Déjà découpés')], default='BATCH_A3', help_text='BATCH_A3: scan par lots à découper | INDIVIDUAL_A4: fichiers déjà découpés par élève', max_length=20, verbose_name="Mode d'upload"),
        ),
        migrations.CreateModel(
            name='ExamPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(help_text="Fichier PDF d'un élève (A4)", upload_to='exams/individual/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), exams.validators.validate_pdf_size, exams.validators.validate_pdf_not_empty, exams.validators.validate_pdf_mime_type, exams.validators.validate_pdf_integrity], verbose_name='Fichier PDF individuel')),
                ('student_identifier', models.CharField(blank=True, help_text='Nom ou identifiant extrait du nom de fichier (optionnel)', max_length=255, null=True, verbose_name='Identifiant élève')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_pdfs', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'PDF Individuel',
                'verbose_name_plural': 'PDFs Individuels',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
