# Generated by Django 4.2.27 on 2026-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_remove_copy_exams_copy_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['exam', 'status'], name='copy_exam_status_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['assigned_corrector', 'status'], name='copy_corrector_status_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['student', 'status'], name='copy_student_status_idx'),
        ),
    ]
