# Generated by Django 4.2.27 on 2026-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_add_upload_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
    ]
