# Generated by Django 4.2.27 on 2026-02-06 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_add_indexes_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='student_csv',
            field=models.FileField(blank=True, help_text="Fichier CSV pour l'identification des élèves (whitelist).", null=True, upload_to='exams/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Fichier CSV des élèves'),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('STAGING', 'En attente'), ('READY', 'Prêt à corriger'), ('LOCKED', 'Verrouillé'), ('GRADING_IN_PROGRESS', 'Correction en cours'), ('GRADING_FAILED', 'Échec de correction'), ('GRADED', 'Corrigé')], db_index=True, default='STAGING', max_length=20, verbose_name='Statut'),
        ),
    ]
