# Generated by Django 4.2.27 on 2026-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_add_results_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='subject_variant',
            field=models.CharField(blank=True, choices=[('A', 'Sujet A'), ('B', 'Sujet B')], help_text="Sujet A ou B, identifié par le correcteur via la référence en bas de l'annexe", max_length=1, null=True, verbose_name='Variante du sujet'),
        ),
    ]
