# Generated by Django 4.2.27 on 2026-02-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_exam_student_csv_alter_copy_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['dispatch_run_id'], name='copy_dispatch_run_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['exam', 'is_identified'], name='copy_exam_identified_idx'),
        ),
    ]
