# Generated by Django 4.2.27 on 2026-02-07 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exams.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_add_state_machine_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSourcePDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(upload_to='exams/source/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), exams.validators.validate_pdf_size, exams.validators.validate_pdf_not_empty, exams.validators.validate_pdf_mime_type, exams.validators.validate_pdf_integrity], verbose_name='Fichier PDF')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nom du fichier original')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('detected_format', models.CharField(choices=[('A3', 'A3'), ('A4', 'A4')], default='A4', max_length=10, verbose_name='Format détecté')),
                ('page_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de pages')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pdfs', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'PDF Source',
                'verbose_name_plural': 'PDFs Source',
                'ordering': ['display_order', 'uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='booklet',
            name='source_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booklets', to='exams.examsourcepdf', verbose_name="PDF source d'origine"),
        ),
    ]
