# Generated by Django 4.2.27 on 2026-02-12 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0020_add_subject_variant_to_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDocumentSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(help_text='Numéro de version (v1, v2, ...)', verbose_name='Version')),
                ('label', models.CharField(blank=True, help_text="Ex: 'BB 2026 J1 - Officiel'", max_length=255, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, help_text='Seule la version active est utilisée par les correcteurs', verbose_name='Version active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_document_sets', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sets', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Lot documentaire',
                'verbose_name_plural': 'Lots documentaires',
                'ordering': ['-version'],
                'unique_together': {('exam', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('sujet', 'Sujet'), ('corrige', 'Corrigé'), ('bareme', 'Barème')], max_length=20, verbose_name='Type de document')),
                ('original_filename', models.CharField(max_length=512, verbose_name='Nom de fichier original')),
                ('storage_path', models.CharField(help_text='Chemin relatif dans MEDIA_ROOT', max_length=1024, verbose_name='Chemin de stockage')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100, verbose_name='Type MIME')),
                ('sha256', models.CharField(help_text='Pour traçabilité et déduplication', max_length=64, verbose_name='Hash SHA-256')),
                ('file_size', models.BigIntegerField(verbose_name='Taille du fichier (octets)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='exams.examdocumentset', verbose_name='Lot documentaire')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': "Document d'examen",
                'verbose_name_plural': "Documents d'examen",
                'ordering': ['doc_type'],
                'unique_together': {('document_set', 'doc_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTextExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('done', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('engine', models.CharField(default='pymupdf', help_text='Ex: pymupdf, pdfminer', max_length=30, verbose_name="Moteur d'extraction")),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('extracted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'extraction")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='exams.examdocument', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Extraction de texte',
                'verbose_name_plural': 'Extractions de texte',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(verbose_name='Numéro de page')),
                ('page_text', models.TextField(verbose_name='Texte de la page')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='exams.documenttextextraction', verbose_name='Extraction')),
            ],
            options={
                'verbose_name': 'Page de document',
                'verbose_name_plural': 'Pages de document',
                'ordering': ['page_number'],
                'unique_together': {('extraction', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('sujet', 'Sujet'), ('corrige', 'Corrigé'), ('bareme', 'Barème')], max_length=20, verbose_name='Type de document source')),
                ('chunk_index', models.PositiveIntegerField(verbose_name='Index du segment')),
                ('page_start', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page de début')),
                ('page_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page de fin')),
                ('exercise_number', models.PositiveIntegerField(blank=True, help_text='Détecté automatiquement lors du chunking', null=True, verbose_name="Numéro d'exercice")),
                ('question_label', models.CharField(blank=True, help_text="Ex: '3b', 'A.1', etc.", max_length=20, verbose_name='Label de question')),
                ('chunk_text', models.TextField(verbose_name='Texte du segment')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags pour filtrage et recherche', verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='exams.documenttextextraction', verbose_name='Extraction')),
            ],
            options={
                'verbose_name': 'Segment de document',
                'verbose_name_plural': 'Segments de document',
                'ordering': ['chunk_index'],
                'unique_together': {('extraction', 'chunk_index')},
            },
        ),
    ]
