# Generated by Django 4.2.27 on 2026-02-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0021_add_examsourcepdf_and_booklet_source_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsourcepdf',
            name='pdf_type',
            field=models.CharField(choices=[('COPY', "Copie d'examen"), ('ANNEXE', 'Annexe')], default='COPY', max_length=10, verbose_name='Type de PDF'),
        ),
    ]
