# Generated by Django 4.2.27 on 2026-02-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_rename_students_st_full_na_idx_students_st_full_na_6ea9f7_idx_and_more'),
        ('exams', '0023_add_results_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='csv_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CSV parsé le'),
        ),
        migrations.AddField(
            model_name='exam',
            name='csv_student_count',
            field=models.IntegerField(default=0, verbose_name="Nombre d'élèves CSV"),
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('STAGING', 'En attente'), ('QUARANTINE', 'Quarantaine OCR'), ('READY', 'Prêt à corriger'), ('LOCKED', 'Verrouillé'), ('GRADING_IN_PROGRESS', 'Correction en cours'), ('GRADING_FAILED', 'Échec de correction'), ('GRADED', 'Corrigé')], db_index=True, default='STAGING', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='AnnexePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_index', models.PositiveIntegerField(verbose_name='Index de page dans le PDF')),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='annexes/pages/', verbose_name='Image de la page')),
                ('header_crop', models.ImageField(blank=True, null=True, upload_to='annexes/headers/', verbose_name="Crop d'en-tête")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('MATCHED', 'Rattachée'), ('QUARANTINE', 'Quarantaine'), ('MANUAL_ASSIGNED', 'Assignée manuellement')], db_index=True, default='PENDING', max_length=20, verbose_name='Statut')),
                ('ocr_confidence', models.FloatField(default=0.0, verbose_name='Confiance OCR')),
                ('ocr_extracted_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nom extrait par OCR')),
                ('ocr_tier', models.CharField(default='LOCAL', max_length=10, verbose_name='Tier OCR')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation")),
                ('copy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annexe_pages', to='exams.copy', verbose_name='Copie rattachée')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annexe_pages', to='exams.exam', verbose_name='Examen')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_annexes', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('source_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annexe_pages', to='exams.examsourcepdf', verbose_name='PDF source')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annexe_pages', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Page annexe',
                'verbose_name_plural': 'Pages annexes',
                'ordering': ['source_pdf', 'page_index'],
                'indexes': [models.Index(fields=['exam', 'status'], name='annexe_exam_status_idx')],
                'unique_together': {('source_pdf', 'page_index')},
            },
        ),
    ]
