# Generated by Django 4.2.29 on 2026-03-25 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0023_copy_performance_indexes_lot8'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code (ex: BAC_BLANC)')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', max_length=20, verbose_name='Couleur UI')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icône UI')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordre de tri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examens",
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JuryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_reports', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_reports', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': 'Rapport de Jury',
                'verbose_name_plural': 'Rapports de Jury',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='exams', to='exams.examtype', verbose_name="Type d'examen"),
        ),
    ]
