# Generated by Django 4.2.29 on 2026-03-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_examtype_juryreport_exam_exam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juryreport',
            name='exam',
        ),
        migrations.AddField(
            model_name='juryreport',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_reports', to='exams.examtype', verbose_name="Type d'Examen"),
        ),
    ]
