# Generated by Django 4.2.29 on 2026-03-28 12:43

from django.db import migrations


def migrate_copy_statuses(apps, schema_editor):
    Copy = apps.get_model('exams', 'Copy')
    db_alias = schema_editor.connection.alias
    Copy.objects.using(db_alias).filter(status='STAGING').update(status='READY')
    Copy.objects.using(db_alias).filter(status='LOCKED').update(status='GRADING_IN_PROGRESS')
    Copy.objects.using(db_alias).filter(status='GRADING_FAILED').update(status='READY')


def reverse_migrate_copy_statuses(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_remove_juryreport_exam_juryreport_exam_type'),
    ]

    operations = [
        migrations.RunPython(migrate_copy_statuses, reverse_migrate_copy_statuses),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=__import__('django.db.models', fromlist=['CharField']).CharField(
                choices=[
                    ('READY', 'Prêt à corriger'),
                    ('GRADING_IN_PROGRESS', 'Correction en cours'),
                    ('GRADED', 'Finalisée'),
                ],
                default='READY',
                max_length=20,
                verbose_name='Statut',
            ),
        ),
    ]
