# Generated by Django 4.2.29 on 2026-03-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_copy_finalizing_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copy',
            name='finalizing_at',
        ),
        migrations.AlterField(
            model_name='copy',
            name='status',
            field=models.CharField(choices=[('READY', 'Pret'), ('IN_PROGRESS', 'En cours'), ('FINALIZED', 'Finalisee')], default='READY', max_length=20, verbose_name='Statut'),
        ),
    ]
