# Generated by Django 4.2.29 on 2026-04-01 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0029_remove_copy_finalizing_at_alter_copy_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroupAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(help_text='Ex: G1, G2, T.04, T.06', max_length=50, verbose_name="Groupe d'élèves")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Correcteur')),
            ],
            options={
                'verbose_name': 'Assignation groupe-correcteur',
                'verbose_name_plural': 'Assignations groupe-correcteur',
                'unique_together': {('teacher', 'group_name')},
            },
        ),
        migrations.CreateModel(
            name='CopyConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_last_name', models.CharField(max_length=255, verbose_name="Nom de l'élève")),
                ('student_first_name', models.CharField(max_length=255, verbose_name="Prénom de l'élève")),
                ('student_dob', models.DateField(verbose_name='Date de naissance')),
                ('reason', models.CharField(blank=True, help_text="Ex: lien familial, conflit d'intérêt", max_length=500, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forbidden_corrector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_constraints', to=settings.AUTH_USER_MODEL, verbose_name='Correcteur interdit')),
            ],
            options={
                'verbose_name': 'Contrainte de dispatch',
                'verbose_name_plural': 'Contraintes de dispatch',
                'unique_together': {('student_last_name', 'student_first_name', 'student_dob', 'forbidden_corrector')},
            },
        ),
    ]
