# Generated by Django 4.2.29 on 2026-04-01 20:05

import datetime
from django.db import migrations


def seed_constraints(apps, schema_editor):
    """Migrate hardcoded INDIVIDUAL_CONSTRAINTS from dispatch_dnb_copies.py."""
    CopyConstraint = apps.get_model('exams', 'CopyConstraint')
    User = apps.get_model('auth', 'User')

    forbidden_emails = [
        'migration-sanitized-001@example.test',
        'migration-sanitized-002@example.test',
        'migration-sanitized-003@example.test',
    ]
    for email in forbidden_emails:
        user = User.objects.filter(username=email).first() or User.objects.filter(email=email).first()
        if user:
            CopyConstraint.objects.get_or_create(
                student_last_name='BEN RHOUMA',
                student_first_name='KAMEL',
                student_dob=datetime.date(2011, 6, 26),
                forbidden_corrector=user,
                defaults={'reason': 'Contrainte individuelle spéciale (lien familial)'},
            )


def seed_teacher_groups(apps, schema_editor):
    """Migrate hardcoded TEACHER_GROUPS from views_my_students.py."""
    TeacherGroupAssignment = apps.get_model('exams', 'TeacherGroupAssignment')
    User = apps.get_model('auth', 'User')

    mappings = {
        'migration-sanitized-004@example.test': 'G3',
        'migration-sanitized-005@example.test': 'G2',
        'migration-sanitized-006@example.test': 'G1',
        'migration-sanitized-007@example.test': 'T.06',
        'migration-sanitized-002@example.test': 'G4',
        'migration-sanitized-001@example.test': 'G6',
        'migration-sanitized-008@example.test': 'G5',
        'migration-sanitized-009@example.test': 'T.04',
    }
    for username, group_name in mappings.items():
        user = User.objects.filter(username=username).first()
        if user:
            TeacherGroupAssignment.objects.get_or_create(
                teacher=user,
                group_name=group_name,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0030_add_copy_constraint_and_teacher_group'),
    ]

    operations = [
        migrations.RunPython(seed_constraints, migrations.RunPython.noop),
        migrations.RunPython(seed_teacher_groups, migrations.RunPython.noop),
    ]
