# Generated by Django 4.2.29 on 2026-04-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0031_seed_copy_constraints_and_teacher_groups'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['student', 'status'], name='idx_copy_student_status'),
        ),
    ]
