# Generated by Django 4.2.29 on 2026-04-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0034_seed_premiere_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='anonymous_id',
            field=models.CharField(max_length=50, verbose_name='Anonymat'),
        ),
        migrations.AlterField(
            model_name='teachergroupassignment',
            name='group_name',
            field=models.CharField(help_text='Ex: G1, G4, selo, 1.02, 3.3, T.04', max_length=50, verbose_name='Groupe ou classe'),
        ),
        migrations.AddConstraint(
            model_name='copy',
            constraint=models.UniqueConstraint(fields=('exam', 'anonymous_id'), name='uq_copy_exam_anonymous_id'),
        ),
    ]
