# Generated by Django 4.2.29 on 2026-04-08 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0035_fix_anonymous_id_unique_per_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'examen"),
        ),
    ]
