# Generated by Django 4.2.30 on 2026-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanreport',
            name='exam_type',
            field=models.CharField(choices=[('DNB_2026', 'DNB 2026'), ('BILAN_BLANC', 'Bilan Blanc'), ('EAM BLANCHE 2026', 'EAM BLANCHE 2026')], max_length=20),
        ),
    ]
