# Generated by Django 4.2.27 on 2026-01-25 21:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0010_exam_correctors'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detected_text', models.TextField(verbose_name='Texte détecté par OCR')),
                ('confidence', models.FloatField(help_text='Valeur entre 0 et 1', verbose_name='Confiance OCR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='exams.copy', verbose_name='Copie')),
                ('suggested_students', models.ManyToManyField(blank=True, related_name='ocr_suggestions', to='students.student', verbose_name='Élèves suggérés')),
            ],
            options={
                'verbose_name': 'Résultat OCR',
                'verbose_name_plural': 'Résultats OCR',
            },
        ),
    ]
