# Generated by Django 4.2.27 on 2026-02-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='manual_override',
            field=models.BooleanField(default=False, help_text="True si l'enseignant a remplacé l'identification OCR manuellement", verbose_name='Remplacement manuel'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='ocr_mode',
            field=models.CharField(choices=[('AUTO', 'Automatique'), ('SEMI_AUTO', 'Semi-automatique'), ('MANUAL', 'Manuel')], default='MANUAL', help_text="Détermine si l'identification est automatique, semi-automatique ou manuelle", max_length=20, verbose_name='Mode OCR'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='selected_candidate_rank',
            field=models.IntegerField(blank=True, help_text="Si l'enseignant sélectionne un candidat de la liste top-k (1-5)", null=True, verbose_name='Rang du candidat sélectionné'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='top_candidates',
            field=models.JSONField(blank=True, default=list, help_text='Liste des top-5 candidats avec scores de consensus', verbose_name='Top-K candidats'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
