# Generated by Django 4.2.27 on 2026-02-06 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_ocrresult_manual_override_ocrresult_ocr_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
