# Generated by Django 4.2.27 on 2026-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0003_alter_ocrresult_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='cloud_raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Réponse brute Document AI'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='extracted_date_of_birth',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Date de naissance extraite'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='extracted_first_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Prénom extrait'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='extracted_last_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom extrait'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='header_crop',
            field=models.ImageField(blank=True, null=True, upload_to='header_crops/', verbose_name="Image d'en-tête recadrée"),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='ocr_tier',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('CLOUD', 'Cloud'), ('MANUAL', 'Manuel')], default='LOCAL', max_length=10, verbose_name='Tier OCR utilisé'),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='processing_time_ms',
            field=models.IntegerField(default=0, verbose_name='Temps de traitement (ms)'),
        ),
    ]
