# Generated by Django 4.2.27 on 2026-01-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Horodatage')),
                ('student_id', models.IntegerField(blank=True, help_text='Si session élève (pas de User Django)', null=True, verbose_name='ID Élève')),
                ('action', models.CharField(db_index=True, help_text='Ex: login.success, copy.download, copy.unlock', max_length=100, verbose_name='Action')),
                ('resource_type', models.CharField(help_text='Ex: Copy, Exam, Student', max_length=50, verbose_name='Type de ressource')),
                ('resource_id', models.CharField(max_length=255, verbose_name='ID Ressource')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(help_text='Navigateur et système', verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données contextuelles additionnelles', verbose_name='Métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'), models.Index(fields=['resource_type', 'resource_id'], name='core_auditl_resourc_a674ad_idx'), models.Index(fields=['student_id', '-timestamp'], name='core_auditl_student_87e450_idx')],
            },
        ),
    ]
