# Generated by Django 4.2.27 on 2026-01-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_add_auditlog_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='Lycée Pierre Mendès France', max_length=255, verbose_name='Nom Etablissement')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Thème par défaut')),
                ('default_exam_duration', models.PositiveIntegerField(default=60, verbose_name='Durée par défaut (min)')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Email')),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configuration Système',
            },
        ),
    ]
